name: stellar_hd_wallet
description: a stellar hd wallet, base on bip39 and stelalr sdkï¼Œyou can use it to generate random mnemonic and get account from mnemonic
version: 1.0.0
author: imloama<imloama@gmail.com>
homepage: https://github.com/imloama/dart-stellar-hd-wallet

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  stellar: any
  bip39: ^1.0.3
  pointycastle: ^1.0.0

dev_dependencies:
  test: ^1.0.0
